spring.application.name=hertzreservation


# ---------------------------------------------------------
# SERVER CONFIGURATION
# ---------------------------------------------------------

# Application port
server.port=8080


# ---------------------------------------------------------
# KAFKA EVENT SERVICE CONFIGURATION
# ---------------------------------------------------------

# URL of kafka-event-service used to publish vehicle events
kafka.event.service.url=http://kafka-event-service:8082/events/vehicle


# ---------------------------------------------------------
# MONGODB CONFIGURATION
# ---------------------------------------------------------

# Local MongoDB connection
#spring.data.mongodb.uri=mongodb://localhost:27017/hertz_db

# Docker MongoDB connection
spring.data.mongodb.uri=mongodb://host.docker.internal:27017/hertz_db

# Automatically create indexes defined in entities
spring.data.mongodb.auto-index-creation=true

# Show MongoDB queries in logs for debugging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG


# ---------------------------------------------------------
# LOGGING CONFIGURATION
# ---------------------------------------------------------

# Default logging level
logging.level.root=INFO

# Enable debug logs for application package
logging.level.com.hertz=DEBUG